services:
  hebpf:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ARCH=aarch64
    image: ebpf:latest
    container_name: ebpfc
    platform: linux/arm64
    privileged: true
    volumes:
      - ../:/hebpf
    command: /sbin/init
    restart: unless-stopped
    networks:
      - hebpfnet
    ports:
      - "8080:8080"
      - "58080:58080"

  prometheus:
    image: prom/prometheus:latest
    container_name: promc
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: unless-stopped
    networks:
      - hebpfnet
    depends_on:
      - hebpf

  grafana:
    image: grafana/grafana:latest
    container_name: grafanac
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning/datasources
    restart: unless-stopped
    networks:
      - hebpfnet
    depends_on:
      - prometheus

  backend1:
    image: httpd:alpine
    container_name: backend1
    privileged: true
    networks:
      - hebpfnet
    command: >
      sh -c "apk update &&
      apk add tcpdump iproute2 &&
      echo '<h1>Backend 1</h1>' > /usr/local/apache2/htdocs/index.html &&
      ip addr add 172.20.0.200/32 dev lo &&
      echo 1 > /proc/sys/net/ipv4/conf/all/arp_ignore &&
      echo 2 > /proc/sys/net/ipv4/conf/all/arp_announce &&
      echo 1 > /proc/sys/net/ipv4/conf/eth0/arp_ignore &&
      echo 2 > /proc/sys/net/ipv4/conf/eth0/arp_announce &&
      httpd-foreground"
    restart: unless-stopped

  backend2:
    image: httpd:alpine
    container_name: backend2
    privileged: true
    networks:
      - hebpfnet
    command: >
      sh -c "apk update &&
      apk add tcpdump iproute2 &&
      echo '<h1>Backend 2</h1>' > /usr/local/apache2/htdocs/index.html &&
      ip addr add 172.20.0.200/32 dev lo &&
      echo 1 > /proc/sys/net/ipv4/conf/all/arp_ignore &&
      echo 2 > /proc/sys/net/ipv4/conf/all/arp_announce &&
      echo 1 > /proc/sys/net/ipv4/conf/eth0/arp_ignore &&
      echo 2 > /proc/sys/net/ipv4/conf/eth0/arp_announce &&
      httpd-foreground"
    restart: unless-stopped

networks:
  hebpfnet:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
