function(generate_ebpf_ids MAP_FILE IDS_HEADER PROG_MAP_HEADER)
  file(STRINGS ${MAP_FILE} LINES)
  set(DEFINES "")
  set(PROG_MAP_ENTRIES "")
  foreach(LINE IN LISTS LINES)
    string(REGEX MATCH "^[^#]" FIRST_CHAR "${LINE}")
    if(NOT FIRST_CHAR)
        continue()
    endif()
    string(REGEX MATCH "([^ ]+) +([0-9]+) +([^ ]+)" _ ${LINE})
    set(NAME ${CMAKE_MATCH_1})
    set(ID ${CMAKE_MATCH_2})
    set(HOOK ${CMAKE_MATCH_3})
    set(DEFINES "${DEFINES}#define EBPF_ID_${NAME} ${ID}\n")
    set(PROG_MAP_ENTRIES "${PROG_MAP_ENTRIES}    { \"${NAME}\", { ${ID}, daemon::HookType::${HOOK} } },\n")
  endforeach()
  configure_file(${CMAKE_SOURCE_DIR}/cmake/ebpf_ids.h.in ${IDS_HEADER} @ONLY)
  configure_file(${CMAKE_SOURCE_DIR}/cmake/ebpf_prog_map.h.in ${PROG_MAP_HEADER} @ONLY)
endfunction()
